openapi: 3.0.3
info:
  title: 广东智能网联
  description: This is a GICC Server based on the OpenAPI 3.0 specification
  version: 1.0.11
servers:
- url: http://localhost:8080
paths:
  /generateSceneData:
    post:
      summary: generate csv files
      operationId: generateCSV
      requestBody:
        $ref: '#/components/requestBodies/scene'
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
        "400":
          description: Invalid status value
      x-swagger-router-controller: Default
components:
  schemas:
    event:
      required:
      - endTime
      - startTime
      type: object
      properties:
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        eventlists:
          type: array
          items:
            $ref: '#/components/schemas/event_eventlists'
    response:
      type: array
      items:
        $ref: '#/components/schemas/response_inner'
    event_eventlists:
      type: object
      properties:
        id:
          type: integer
        type:
          type: integer
        trigger_time:
          type: string
          format: date-time
        create_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
        status:
          type: integer
        address:
          type: string
        longitude:
          type: integer
        latitude:
          type: integer
        crossID:
          type: integer
        esn:
          type: string
    response_inner:
      type: object
      properties:
        evnetID:
          type: integer
        csvUrl:
          type: string
      example:
        csvUrl: csvUrl
        evnetID: 0
  requestBodies:
    scene:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/event'
